#
# ~/.bashrc (root)
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

export EDITOR="/usr/bin/nano"
export VISUAL="/usr/bin/nano"

PS1="\[$(tput bold)\]\[\033[38;5;226m\]󰮯  \[$(tput bold)\]\[\033[38;5;39m\]󰊠  \[$(tput bold)\]\[\033[38;5;39m\]󰊠  \[$(tput bold)\]\[\033[38;5;39m\]󰊠  \[$(tput bold)\]\[\033[38;5;39m\]󰊠  \[$(tput bold)\]\[\033[38;5;197m\]\w\[$(tput sgr0)\] "

if command -v fish >/dev/null 2>&1; then
    exec fish
fi
