#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias su='sudo su'

export EDITOR=nano
export VISUAL=nano

PS1="\[$(tput bold)\]\[\033[38;5;208m\]󰊠  \[$(tput bold)\]\[\033[38;5;196m\]󰊠  \[$(tput bold)\]\[\033[38;5;219m\]󰊠  \[$(tput bold)\]\[\033[38;5;87m\]󰊠  \[$(tput bold)\]\[\033[38;5;226m\]󰮯  \[\033[38;5;226m\]\w\[$(tput sgr0)\] "

if command -v fish >/dev/null 2>&1; then
    exec fish
fi
